apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  namespace: default
  name: my-backendconfig
# cloud-armor
spec:
  securityPolicy:
    name: test
# iap
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: my-secret
